import { NextRequest, NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import path from "node:path";
import {
  decodeDigitalOrderPayload,
  wasDigitalItemPurchased,
  computeTrustedDigitalTotal,
} from "../../../lib/digital/order-payload";
import { verifyTransaction } from "../../../lib/payments/oreem-client";
import { watermarkPdf } from "../../../lib/digital/watermark-pdf";
import { digitalFileName } from "../../../lib/digital/catalog";
import type { DigitalLanguage, DigitalTopicId } from "../../../lib/digital/types";

export const runtime = "nodejs";
// pdf-lib's load+watermark+save on every request risks a timeout on a cold serverless
// start under Vercel's default duration budget; give it explicit headroom.
export const maxDuration = 60;

const VALID_TOPIC_IDS = new Set<DigitalTopicId>([
  "picky-eating",
  "potty-training",
  "screens-big-feelings",
  "sharing-sibling-conflict",
  "sleep-bedtime",
  "starting-school",
  "child-hits",
  "school-season-toolkit",
  "activity-book",
]);

export async function GET(request: NextRequest) {
  const encodedOrder = request.nextUrl.searchParams.get("order");
  const product = request.nextUrl.searchParams.get("product");
  const language = request.nextUrl.searchParams.get("language");

  if (
    !encodedOrder ||
    !product ||
    !VALID_TOPIC_IDS.has(product as DigitalTopicId) ||
    (language !== "ar" && language !== "en")
  ) {
    return NextResponse.json({ error: "invalid_request" }, { status: 400 });
  }

  const payload = decodeDigitalOrderPayload(encodedOrder);
  if (!payload) {
    return NextResponse.json({ error: "invalid_request" }, { status: 400 });
  }

  // Defence in depth: every txnRef this route should ever see was generated by
  // app/api/orders/digital-oreem/route.ts, which always prefixes it "peepdigi_". This
  // stops a digital-download request from ever being pointed at a physical-box order's
  // txnRef (or any other namespace), regardless of amount coincidences, before we even
  // make a network call to Oreem.
  if (!payload.txnRef.startsWith("peepdigi_")) {
    return NextResponse.json({ error: "invalid_request" }, { status: 400 });
  }

  // Never trust the confirmation page or the URL alone — independently re-verify the
  // payment before serving anything, same fail-closed pattern as the physical box's
  // confirmation page.
  let verification;
  try {
    verification = await verifyTransaction(payload.txnRef);
  } catch (error) {
    console.error("Failed to verify Oreem transaction for digital download", error);
    return NextResponse.json({ error: "verification_failed" }, { status: 502 });
  }

  if (!verification.verified) {
    return NextResponse.json({ error: "payment_not_verified" }, { status: 403 });
  }

  // payload.totalBhd is unsigned client-controlled input and must never be trusted
  // directly — a forged unitPriceBhd on an item (e.g. claiming the bundle costs the
  // price of one topic) would leave totalBhd looking consistent while granting access
  // to items never actually paid for. Compare Oreem's verified amount against the
  // CATALOG-derived trusted total instead.
  const trustedTotalBhd = computeTrustedDigitalTotal(payload.items);
  // An undefined amountBhd means Oreem's response carried no usable amount for an
  // otherwise-verified transaction — that must be treated as a binding-check FAILURE,
  // not silently skipped, or a verified-but-amount-less response would let any item
  // claim through unchecked.
  if (
    verification.amountBhd === undefined ||
    !(
      Number.isFinite(trustedTotalBhd) &&
      Math.abs(verification.amountBhd - trustedTotalBhd) <= 0.001
    )
  ) {
    console.error("Oreem verified amount does not match digital order trusted total", {
      txnRef: payload.txnRef,
      verifiedAmount: verification.amountBhd,
      trustedTotalBhd,
      payloadTotal: payload.totalBhd,
    });
    return NextResponse.json({ error: "amount_mismatch" }, { status: 403 });
  }

  // Confirm the requested product/language was actually part of what this txnRef paid
  // for — either as its own line, or covered by a bundle purchase in the same language.
  const topicId = product as DigitalTopicId;
  if (!wasDigitalItemPurchased(payload, topicId, language as DigitalLanguage)) {
    return NextResponse.json({ error: "not_purchased" }, { status: 403 });
  }

  const fileName = digitalFileName(topicId, language as DigitalLanguage);
  const filePath = path.join(process.cwd(), "content", "digital-products", fileName);

  let sourceBytes: Buffer;
  try {
    sourceBytes = await readFile(filePath);
  } catch (error) {
    console.error("Failed to read digital product source file", { fileName, error });
    return NextResponse.json({ error: "file_unavailable" }, { status: 500 });
  }

  let watermarked: Buffer;
  try {
    watermarked = await watermarkPdf(sourceBytes, `Peep & beyond - Order ${payload.txnRef}`);
  } catch (error) {
    console.error("Failed to watermark digital product file", { fileName, error });
    return NextResponse.json({ error: "watermark_failed" }, { status: 500 });
  }

  return new NextResponse(new Uint8Array(watermarked), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "private, no-store",
    },
  });
}
