export interface Country {
  code: string;
  labelAr: string;
  labelEn: string;
}

// GCC countries first (closest to home base and highest order volume), then the
// rest of the world alphabetically by Arabic name. Generated from ISO 3166-1
// alpha-2 codes via Intl.DisplayNames so the Arabic/English names match the
// browser's own locale data instead of a hand-maintained translation list.
export const COUNTRIES: Country[] = [
  { code: "BH", labelAr: "البحرين", labelEn: "Bahrain" },
  { code: "SA", labelAr: "المملكة العربية السعودية", labelEn: "Saudi Arabia" },
  { code: "AE", labelAr: "الإمارات العربية المتحدة", labelEn: "United Arab Emirates" },
  { code: "KW", labelAr: "الكويت", labelEn: "Kuwait" },
  { code: "OM", labelAr: "عُمان", labelEn: "Oman" },
  { code: "QA", labelAr: "قطر", labelEn: "Qatar" },
  { code: "IS", labelAr: "آيسلندا", labelEn: "Iceland" },
  { code: "ET", labelAr: "إثيوبيا", labelEn: "Ethiopia" },
  { code: "AZ", labelAr: "أذربيجان", labelEn: "Azerbaijan" },
  { code: "AM", labelAr: "أرمينيا", labelEn: "Armenia" },
  { code: "ER", labelAr: "إريتريا", labelEn: "Eritrea" },
  { code: "ES", labelAr: "إسبانيا", labelEn: "Spain" },
  { code: "AU", labelAr: "أستراليا", labelEn: "Australia" },
  { code: "EE", labelAr: "إستونيا", labelEn: "Estonia" },
  { code: "IL", labelAr: "إسرائيل", labelEn: "Israel" },
  { code: "SZ", labelAr: "إسواتيني", labelEn: "Eswatini" },
  { code: "AF", labelAr: "أفغانستان", labelEn: "Afghanistan" },
  { code: "PS", labelAr: "الأراضي الفلسطينية", labelEn: "Palestinian Territories" },
  { code: "AR", labelAr: "الأرجنتين", labelEn: "Argentina" },
  { code: "JO", labelAr: "الأردن", labelEn: "Jordan" },
  { code: "EC", labelAr: "الإكوادور", labelEn: "Ecuador" },
  { code: "AL", labelAr: "ألبانيا", labelEn: "Albania" },
  { code: "BR", labelAr: "البرازيل", labelEn: "Brazil" },
  { code: "PT", labelAr: "البرتغال", labelEn: "Portugal" },
  { code: "BA", labelAr: "البوسنة والهرسك", labelEn: "Bosnia & Herzegovina" },
  { code: "CZ", labelAr: "التشيك", labelEn: "Czechia" },
  { code: "ME", labelAr: "الجبل الأسود", labelEn: "Montenegro" },
  { code: "DZ", labelAr: "الجزائر", labelEn: "Algeria" },
  { code: "DK", labelAr: "الدانمرك", labelEn: "Denmark" },
  { code: "CV", labelAr: "الرأس الأخضر", labelEn: "Cape Verde" },
  { code: "SV", labelAr: "السلفادور", labelEn: "El Salvador" },
  { code: "SN", labelAr: "السنغال", labelEn: "Senegal" },
  { code: "SD", labelAr: "السودان", labelEn: "Sudan" },
  { code: "SE", labelAr: "السويد", labelEn: "Sweden" },
  { code: "SO", labelAr: "الصومال", labelEn: "Somalia" },
  { code: "CN", labelAr: "الصين", labelEn: "China" },
  { code: "IQ", labelAr: "العراق", labelEn: "Iraq" },
  { code: "GA", labelAr: "الغابون", labelEn: "Gabon" },
  { code: "VA", labelAr: "الفاتيكان", labelEn: "Vatican City" },
  { code: "PH", labelAr: "الفلبين", labelEn: "Philippines" },
  { code: "CM", labelAr: "الكاميرون", labelEn: "Cameroon" },
  { code: "CG", labelAr: "الكونغو - برازافيل", labelEn: "Congo - Brazzaville" },
  { code: "CD", labelAr: "الكونغو - كينشاسا", labelEn: "Congo - Kinshasa" },
  { code: "DE", labelAr: "ألمانيا", labelEn: "Germany" },
  { code: "MA", labelAr: "المغرب", labelEn: "Morocco" },
  { code: "MX", labelAr: "المكسيك", labelEn: "Mexico" },
  { code: "GB", labelAr: "المملكة المتحدة", labelEn: "United Kingdom" },
  { code: "NO", labelAr: "النرويج", labelEn: "Norway" },
  { code: "AT", labelAr: "النمسا", labelEn: "Austria" },
  { code: "NE", labelAr: "النيجر", labelEn: "Niger" },
  { code: "IN", labelAr: "الهند", labelEn: "India" },
  { code: "US", labelAr: "الولايات المتحدة", labelEn: "United States" },
  { code: "JP", labelAr: "اليابان", labelEn: "Japan" },
  { code: "YE", labelAr: "اليمن", labelEn: "Yemen" },
  { code: "GR", labelAr: "اليونان", labelEn: "Greece" },
  { code: "AG", labelAr: "أنتيغوا وبربودا", labelEn: "Antigua & Barbuda" },
  { code: "AD", labelAr: "أندورا", labelEn: "Andorra" },
  { code: "ID", labelAr: "إندونيسيا", labelEn: "Indonesia" },
  { code: "AO", labelAr: "أنغولا", labelEn: "Angola" },
  { code: "UY", labelAr: "أورغواي", labelEn: "Uruguay" },
  { code: "UZ", labelAr: "أوزبكستان", labelEn: "Uzbekistan" },
  { code: "UG", labelAr: "أوغندا", labelEn: "Uganda" },
  { code: "UA", labelAr: "أوكرانيا", labelEn: "Ukraine" },
  { code: "IR", labelAr: "إيران", labelEn: "Iran" },
  { code: "IE", labelAr: "أيرلندا", labelEn: "Ireland" },
  { code: "IT", labelAr: "إيطاليا", labelEn: "Italy" },
  { code: "PG", labelAr: "بابوا غينيا الجديدة", labelEn: "Papua New Guinea" },
  { code: "PY", labelAr: "باراغواي", labelEn: "Paraguay" },
  { code: "PK", labelAr: "باكستان", labelEn: "Pakistan" },
  { code: "PW", labelAr: "بالاو", labelEn: "Palau" },
  { code: "BB", labelAr: "بربادوس", labelEn: "Barbados" },
  { code: "BN", labelAr: "بروناي", labelEn: "Brunei" },
  { code: "BE", labelAr: "بلجيكا", labelEn: "Belgium" },
  { code: "BG", labelAr: "بلغاريا", labelEn: "Bulgaria" },
  { code: "BZ", labelAr: "بليز", labelEn: "Belize" },
  { code: "BD", labelAr: "بنغلاديش", labelEn: "Bangladesh" },
  { code: "PA", labelAr: "بنما", labelEn: "Panama" },
  { code: "BJ", labelAr: "بنين", labelEn: "Benin" },
  { code: "BT", labelAr: "بوتان", labelEn: "Bhutan" },
  { code: "BW", labelAr: "بوتسوانا", labelEn: "Botswana" },
  { code: "BF", labelAr: "بوركينا فاسو", labelEn: "Burkina Faso" },
  { code: "BI", labelAr: "بوروندي", labelEn: "Burundi" },
  { code: "PL", labelAr: "بولندا", labelEn: "Poland" },
  { code: "BO", labelAr: "بوليفيا", labelEn: "Bolivia" },
  { code: "PE", labelAr: "بيرو", labelEn: "Peru" },
  { code: "BY", labelAr: "بيلاروس", labelEn: "Belarus" },
  { code: "TH", labelAr: "تايلاند", labelEn: "Thailand" },
  { code: "TW", labelAr: "تايوان", labelEn: "Taiwan" },
  { code: "TM", labelAr: "تركمانستان", labelEn: "Turkmenistan" },
  { code: "TR", labelAr: "تركيا", labelEn: "Türkiye" },
  { code: "TT", labelAr: "ترينيداد وتوباغو", labelEn: "Trinidad & Tobago" },
  { code: "TD", labelAr: "تشاد", labelEn: "Chad" },
  { code: "CL", labelAr: "تشيلي", labelEn: "Chile" },
  { code: "TZ", labelAr: "تنزانيا", labelEn: "Tanzania" },
  { code: "TG", labelAr: "توغو", labelEn: "Togo" },
  { code: "TV", labelAr: "توفالو", labelEn: "Tuvalu" },
  { code: "TN", labelAr: "تونس", labelEn: "Tunisia" },
  { code: "TO", labelAr: "تونغا", labelEn: "Tonga" },
  { code: "TL", labelAr: "تيمور - ليشتي", labelEn: "Timor-Leste" },
  { code: "JM", labelAr: "جامايكا", labelEn: "Jamaica" },
  { code: "BS", labelAr: "جزر البهاما", labelEn: "Bahamas" },
  { code: "KM", labelAr: "جزر القمر", labelEn: "Comoros" },
  { code: "MV", labelAr: "جزر المالديف", labelEn: "Maldives" },
  { code: "SB", labelAr: "جزر سليمان", labelEn: "Solomon Islands" },
  { code: "MH", labelAr: "جزر مارشال", labelEn: "Marshall Islands" },
  { code: "CF", labelAr: "جمهورية أفريقيا الوسطى", labelEn: "Central African Republic" },
  { code: "DO", labelAr: "جمهورية الدومينيكان", labelEn: "Dominican Republic" },
  { code: "ZA", labelAr: "جنوب أفريقيا", labelEn: "South Africa" },
  { code: "SS", labelAr: "جنوب السودان", labelEn: "South Sudan" },
  { code: "GE", labelAr: "جورجيا", labelEn: "Georgia" },
  { code: "DJ", labelAr: "جيبوتي", labelEn: "Djibouti" },
  { code: "DM", labelAr: "دومينيكا", labelEn: "Dominica" },
  { code: "RW", labelAr: "رواندا", labelEn: "Rwanda" },
  { code: "RU", labelAr: "روسيا", labelEn: "Russia" },
  { code: "RO", labelAr: "رومانيا", labelEn: "Romania" },
  { code: "ZM", labelAr: "زامبيا", labelEn: "Zambia" },
  { code: "ZW", labelAr: "زيمبابوي", labelEn: "Zimbabwe" },
  { code: "CI", labelAr: "ساحل العاج", labelEn: "Côte d’Ivoire" },
  { code: "WS", labelAr: "ساموا", labelEn: "Samoa" },
  { code: "SM", labelAr: "سان مارينو", labelEn: "San Marino" },
  { code: "VC", labelAr: "سانت فنسنت وجزر غرينادين", labelEn: "St. Vincent & Grenadines" },
  { code: "KN", labelAr: "سانت كيتس ونيفيس", labelEn: "St. Kitts & Nevis" },
  { code: "LC", labelAr: "سانت لوسيا", labelEn: "St. Lucia" },
  { code: "ST", labelAr: "ساو تومي وبرينسيبي", labelEn: "São Tomé & Príncipe" },
  { code: "LK", labelAr: "سريلانكا", labelEn: "Sri Lanka" },
  { code: "SK", labelAr: "سلوفاكيا", labelEn: "Slovakia" },
  { code: "SI", labelAr: "سلوفينيا", labelEn: "Slovenia" },
  { code: "SG", labelAr: "سنغافورة", labelEn: "Singapore" },
  { code: "SY", labelAr: "سوريا", labelEn: "Syria" },
  { code: "SR", labelAr: "سورينام", labelEn: "Suriname" },
  { code: "CH", labelAr: "سويسرا", labelEn: "Switzerland" },
  { code: "SL", labelAr: "سيراليون", labelEn: "Sierra Leone" },
  { code: "SC", labelAr: "سيشل", labelEn: "Seychelles" },
  { code: "RS", labelAr: "صربيا", labelEn: "Serbia" },
  { code: "TJ", labelAr: "طاجيكستان", labelEn: "Tajikistan" },
  { code: "GM", labelAr: "غامبيا", labelEn: "Gambia" },
  { code: "GH", labelAr: "غانا", labelEn: "Ghana" },
  { code: "GD", labelAr: "غرينادا", labelEn: "Grenada" },
  { code: "GT", labelAr: "غواتيمالا", labelEn: "Guatemala" },
  { code: "GY", labelAr: "غيانا", labelEn: "Guyana" },
  { code: "GN", labelAr: "غينيا", labelEn: "Guinea" },
  { code: "GQ", labelAr: "غينيا الاستوائية", labelEn: "Equatorial Guinea" },
  { code: "GW", labelAr: "غينيا بيساو", labelEn: "Guinea-Bissau" },
  { code: "VU", labelAr: "فانواتو", labelEn: "Vanuatu" },
  { code: "FR", labelAr: "فرنسا", labelEn: "France" },
  { code: "VE", labelAr: "فنزويلا", labelEn: "Venezuela" },
  { code: "FI", labelAr: "فنلندا", labelEn: "Finland" },
  { code: "VN", labelAr: "فيتنام", labelEn: "Vietnam" },
  { code: "FJ", labelAr: "فيجي", labelEn: "Fiji" },
  { code: "CY", labelAr: "قبرص", labelEn: "Cyprus" },
  { code: "KG", labelAr: "قيرغيزستان", labelEn: "Kyrgyzstan" },
  { code: "KZ", labelAr: "كازاخستان", labelEn: "Kazakhstan" },
  { code: "HR", labelAr: "كرواتيا", labelEn: "Croatia" },
  { code: "KH", labelAr: "كمبوديا", labelEn: "Cambodia" },
  { code: "CA", labelAr: "كندا", labelEn: "Canada" },
  { code: "CU", labelAr: "كوبا", labelEn: "Cuba" },
  { code: "KR", labelAr: "كوريا الجنوبية", labelEn: "South Korea" },
  { code: "KP", labelAr: "كوريا الشمالية", labelEn: "North Korea" },
  { code: "CR", labelAr: "كوستاريكا", labelEn: "Costa Rica" },
  { code: "CO", labelAr: "كولومبيا", labelEn: "Colombia" },
  { code: "KI", labelAr: "كيريباتي", labelEn: "Kiribati" },
  { code: "KE", labelAr: "كينيا", labelEn: "Kenya" },
  { code: "LV", labelAr: "لاتفيا", labelEn: "Latvia" },
  { code: "LA", labelAr: "لاوس", labelEn: "Laos" },
  { code: "LB", labelAr: "لبنان", labelEn: "Lebanon" },
  { code: "LU", labelAr: "لوكسمبورغ", labelEn: "Luxembourg" },
  { code: "LY", labelAr: "ليبيا", labelEn: "Libya" },
  { code: "LR", labelAr: "ليبيريا", labelEn: "Liberia" },
  { code: "LT", labelAr: "ليتوانيا", labelEn: "Lithuania" },
  { code: "LI", labelAr: "ليختنشتاين", labelEn: "Liechtenstein" },
  { code: "LS", labelAr: "ليسوتو", labelEn: "Lesotho" },
  { code: "MT", labelAr: "مالطا", labelEn: "Malta" },
  { code: "ML", labelAr: "مالي", labelEn: "Mali" },
  { code: "MY", labelAr: "ماليزيا", labelEn: "Malaysia" },
  { code: "MG", labelAr: "مدغشقر", labelEn: "Madagascar" },
  { code: "EG", labelAr: "مصر", labelEn: "Egypt" },
  { code: "MK", labelAr: "مقدونيا الشمالية", labelEn: "North Macedonia" },
  { code: "MW", labelAr: "ملاوي", labelEn: "Malawi" },
  { code: "MN", labelAr: "منغوليا", labelEn: "Mongolia" },
  { code: "MR", labelAr: "موريتانيا", labelEn: "Mauritania" },
  { code: "MU", labelAr: "موريشيوس", labelEn: "Mauritius" },
  { code: "MZ", labelAr: "موزمبيق", labelEn: "Mozambique" },
  { code: "MD", labelAr: "مولدوفا", labelEn: "Moldova" },
  { code: "MC", labelAr: "موناكو", labelEn: "Monaco" },
  { code: "MM", labelAr: "ميانمار (بورما)", labelEn: "Myanmar (Burma)" },
  { code: "FM", labelAr: "ميكرونيزيا", labelEn: "Micronesia" },
  { code: "NA", labelAr: "ناميبيا", labelEn: "Namibia" },
  { code: "NR", labelAr: "ناورو", labelEn: "Nauru" },
  { code: "NP", labelAr: "نيبال", labelEn: "Nepal" },
  { code: "NG", labelAr: "نيجيريا", labelEn: "Nigeria" },
  { code: "NI", labelAr: "نيكاراغوا", labelEn: "Nicaragua" },
  { code: "NZ", labelAr: "نيوزيلندا", labelEn: "New Zealand" },
  { code: "HT", labelAr: "هايتي", labelEn: "Haiti" },
  { code: "HN", labelAr: "هندوراس", labelEn: "Honduras" },
  { code: "HU", labelAr: "هنغاريا", labelEn: "Hungary" },
  { code: "NL", labelAr: "هولندا", labelEn: "Netherlands" },
];

export function isGccCountry(countryCode: string): boolean {
  return ["BH", "SA", "AE", "KW", "OM", "QA"].includes(countryCode);
}
